Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Reposatries;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using session3Mvc.Helpers;
using session3Mvc.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace session3Mvc.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        //private readonly IEmpeloyeeReposatry _empeloyeeReposatry;
        //private readonly IDepartmentReposatry _departmentReposatry;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper) // asking clr to create object from IDepartmentReposatry and assign his adr
        {
            //_empeloyeeReposatry = empeloyeeReposatry;
            //_departmentReposatry = departmentReposatry;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public async Task< IActionResult> Index(string SearchValue)
        {
            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))
            {
                 employees =await _unitOfWork.EmpeloyeeReposatry.GetAll();
            }
            else
            {
                 employees= _unitOfWork.EmpeloyeeReposatry.SearchEmployeesByName(SearchValue);

            }
            var mappedEmps = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
            return View(mappedEmps);

        }
        //[HttpGet]
        public  async Task <IActionResult> Create()
        {
            ViewBag.Departments=await _unitOfWork.DepartmentReposatry.GetAll();
            return View();

        }

        [HttpPost]
        public async Task< IActionResult> Create(EmployeeViewModel employeeVM)
        {
            ///manual Mapping::
            ///var employee = new Employee()
            ///{
            ///    Name = employeeVM.Name,
            ///   Address = employeeVM.Address,
            ///    Email = employeeVM.Email,
            ///    Salary = employeeVM.Salary,
            ///    Age = employeeVM.Age,
            ///    DepartmentId = employeeVM.DepartmentId,
            ///    IsActive = employeeVM.IsActive,
            ///    HireDate = employeeVM.HireDate,
            ///   PhoneNumber = employeeVM.PhoneNumber
            ///};
             
            employeeVM.ImageName = DoucmentSettings.UploadFile(employeeVM.Image, "images");
            var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
            if (ModelState.IsValid)
            {

                _unitOfWork.EmpeloyeeReposatry.Add(mappedEmp);
                int count =await _unitOfWork.Complete();
                if (count > 0)
                {
                    TempData["Message"] = "Employee created succesfully";
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mappedEmp);
        }

        //[HttpGet]
        public async Task< IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var employee =await _unitOfWork.EmpeloyeeReposatry.GetById(id.Value);
            if (employee is null)
            {
                return NotFound();
            }

            var mappedEmp=_mapper.Map<Employee, EmployeeViewModel>(employee);
            return View(ViewName, mappedEmp);

        }
        public async Task  <IActionResult> Edit(int? id)
        {
            //if (id is null)
            //    return BadRequest();
            //var department = _departmentRepositry.GetById(id.Value);
            //if (department is null)
            //{
            //    return NotFound();
            //}
            //return View(department);
            ViewBag.Departments = await _unitOfWork.DepartmentReposatry.GetAll();
            return await Details(id, "Edit");


        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    employeeVM.ImageName = DoucmentSettings.UploadFile(employeeVM.Image, "images");
                    var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                    _unitOfWork.EmpeloyeeReposatry.Update(mappedEmp);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception ex)
                {
                    //1.log exception
                    //2. frindly message

                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(employeeVM);

        }



        [HttpGet]
        public  async Task< IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");

        }
        [HttpPost]
        public async Task< IActionResult> Delete(EmployeeViewModel employeeVM)
        {
            try
            {
                var mappedEmp = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                 _unitOfWork.EmpeloyeeReposatry.Delete(mappedEmp);
                int count =await _unitOfWork.Complete();
                if (count > 0)
                    DoucmentSettings.DeleteFile(employeeVM.ImageName, "images");
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {
                //1.log exception
                //2. frindly message

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employeeVM);
            }
        }
    }

}

Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using session3Mvc.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace session3Mvc.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager , IMapper mapper)
        {
            _roleManager = roleManager;
            _mapper = mapper;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task< IActionResult> Create(RoleViewModel model)
        {

            if (ModelState.IsValid)
            {
                var mappedRole = _mapper.Map<RoleViewModel , IdentityRole>(model);

                await _roleManager.CreateAsync(mappedRole);
                return RedirectToAction(nameof(Index));

            }
            return View(model);
        }
        public async Task<IActionResult> Index(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                var roles = await _roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id = R.Id,
                    RoleName=R.Name
                }).ToListAsync();
                return View(roles);
            }
            else
            {
                var role = await _roleManager.FindByNameAsync(name);
                var mappedRole = new RoleViewModel()
                {
                    Id = role.Id,
                    RoleName=role.Name
                };
                return View(new List<RoleViewModel>() { mappedRole });
            }
        }

        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var role = await _roleManager.FindByIdAsync(id);
            if (role is null)
            {
                return NotFound();
            }

            var mappedUser = _mapper.Map<IdentityRole, RoleViewModel>(role);
            return View(ViewName, mappedUser);

        }

        public async Task<IActionResult> Edit(string? id)
        {

            return await Details(id, "Edit");


        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel updatedRole)
        {
            if (id != updatedRole.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var Role = await _roleManager.FindByIdAsync(id);
                    Role.Name = updatedRole.RoleName;
                   
                    //user.Email = updatedUser.Email;
                    //user.SecurityStamp=Guid.NewGuid().ToString();

                    await _roleManager.UpdateAsync(Role);

                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception ex)
                {
                    //1.log exception
                    //2. frindly message

                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(updatedRole);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");

        }
        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(string id)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(role);

                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {
                //1.log exception
                //2. frindly message

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }
        }

    }
}

Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using session3Mvc.Helpers;
using session3Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace session3Mvc.Controllers
{
	public class UserController: Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager , SignInManager<ApplicationUser> signInManager ,IMapper mapper)
        {
			_userManager = userManager;
			_signInManager = signInManager;
            _mapper = mapper;
        }

		public async Task< IActionResult> Index(string email)
		{
			if(string.IsNullOrEmpty(email))
			{
				var users =await _userManager.Users.Select(u=> new UserViewModel()
				{
					Id = u.Id,
					FName=u.FName,
					LName=u.LName,
					Email=u.Email,
					PhoneNumber=u.PhoneNumber,
					Roles= _userManager.GetRolesAsync(u).Result 
				}).ToListAsync();
				return View(users);
			}
			else
			{
				var user =await _userManager.FindByEmailAsync(email);
				var mappedUser = new UserViewModel()
				{
					Id = user.Id ,
					FName = user.FName,
					LName = user.LName,
					Email = user.Email,
					PhoneNumber = user.PhoneNumber,
					Roles = _userManager.GetRolesAsync(user).Result
				};
				return View(new List<UserViewModel>() {mappedUser });
			}
		}

        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var user = await _userManager.FindByIdAsync(id);
            if (user is null)
            {
                return NotFound();
            }

			var mappedUser = _mapper.Map < ApplicationUser, UserViewModel>(user);
            return View(ViewName, mappedUser);

        }

        public async Task<IActionResult> Edit(string? id)
        {
            
            return await Details(id, "Edit");


        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task< IActionResult> Edit([FromRoute] string id, UserViewModel updatedUser)
        {
            if (id != updatedUser.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    user.FName = updatedUser.FName;
                    user.LName = updatedUser.LName;
                    user.PhoneNumber = updatedUser.PhoneNumber;
                    //user.Email = updatedUser.Email;
                    //user.SecurityStamp=Guid.NewGuid().ToString();

                    await _userManager.UpdateAsync(user);

                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception ex)
                {
                    //1.log exception
                    //2. frindly message

                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(updatedUser);

        }

        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");

        }
        [HttpPost]
        public async Task<IActionResult> ConfirmDelete( string id)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);
                await _userManager.DeleteAsync(user);
                
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {
                //1.log exception
                //2. frindly message

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }
        }

    }
}

Views/Shared/AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative SignUp Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

Views/Shared/_ButtonsPartiaViel.cshtml
@model string

<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning"><i class="fas fa-eye"></i>Details</a>
</td>
<td>
    <a asp-action="Edit"  asp-route-id="@Model" class="btn btn-primary"><i class="fas fa-edit"></i>Update</a>
</td>
<td>
    <a asp-action="Delete"  asp-route-id="@Model" class="btn btn-danger"><i class="fas fa-trash"></i>delete</a>
</td>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - session2MvcPart2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>